### ISSUE TITLE
Comparison with rollover plugin

### ISSUE THREAD

**Issue by Rhydderch** [Newbrict/obsidian-obligator#1]
Hi,

I was wondering whether you could add a comparison of your plugin to the rollover todo plugin.
Both seem to want to do the same thing so I think it would be useful for me and other users to know what your plugin does differently.

Thanks in advance

**Comment by Newbrict** [comment]
Hi, I'll write more about this later, but the biggest difference is that the rollover-daily-todos only copies over check boxes, whereas obligator will copy over all of your headers and notes in between the specified headers. This lets you organize your to-do list with markdown. In fact, this was the feature that was missing from rollover-daily-todos which motivated me to write this plugin.

Also rollover-daily-todos relies on the daily notes plugin, obligator is a total replacement.

I don't recall if there's an old note archiving feature, but obsidian has one.

Next week I'm going to be adding a feature for recurring to-do list items.

**Comment by Newbrict** [comment]
@Rhydderch Check out the documentation for the {{ obligate * * * }} template. That is a pretty substantial difference!
