### ISSUE TITLE
If top-level to-do item is NOT "complete", copy ALL sub-items (regardless of the sub-item's status)

### ISSUE THREAD

**Issue by vogelap** [Newbrict/obsidian-obligator#13]
As a user, if the top top-level to-do item has any status OTHER THAN "complete", when rolling over from day-to-day, copy ALL sub-item(s) associated with that top-level to-do item to the new daily note REGARDLESS of the status of the sub-item(s).

I use the top-level to-do item as a Project. Sub-items are tasks associated with the project, and it is useful for me to see the historical activity until the task is done.

Here are a couple screenshots (redacted) displaying the CURRENT Obligator behavior and the DESIRED Obligator behavior, from my perspective.

**CURRENT BEHAVIOR**:
![CURRENT Rollover](https://github.com/Newbrict/obsidian-obligator/assets/1869371/5f3986ae-e577-4511-9725-7b589a8faa84)

**DESIRED BEHAVIOR**:
![DESIRED Rollover](https://github.com/Newbrict/obsidian-obligator/assets/1869371/382ca616-3fa5-4777-abff-6202d2e938b8)

**Comment by vogelap** [comment]
> Also, regarding https://github.com/Newbrict/obsidian-obligator/issues/13, which is related, checked items are intended to be wiped away at the start of a new note, unless it would break the hierarchy of items (i.e. a parent checked off but not the children). That's why there is a new note made every day while retaining the old notes -- so that each day you start with a fresh view of your obligations, but with the freedom to look back in the history to see what's been done.

This historic view functionality is crucial to my use case, so if this behavior could be configurable, that would serve my use case really well.

**Comment by Newbrict** [comment]
This is now available in version 3.18.0

Please test and let me know if you have any issues.

**Comment by vogelap** [comment]
Thank you! I used it this morning, and it is working great. I will keep an eye on it and let you know if I spot any issues. 

Having this historical rollover and Obligator's ability to copy all non-complete tags is awesome for my workflow. 

THANK YOU!
