### ISSUE TITLE
Commit be3bb0c breaks Obligator because it recurses subfolders (that have matching filenames that aren't Obligator notes)

### ISSUE THREAD

**Issue by daniel347x** [Newbrict/obsidian-obligator#14]
Greetings! With sincere apologies that I do not have time to do more than report what I think is the origin of Obligator breaking on my system, this is a quick report.

Now, when I click the Obligator carrot, I receive this error popup:

![image](https://github.com/Newbrict/obsidian-obligator/assets/309746/01b1e417-1c18-4722-b072-4d6b1584c0ea)

(Notice the filename: `Pasted Image 20231021233045_222`)

...which corresponds to this line of code in main.ts where this very error is reported:

![image](https://github.com/Newbrict/obsidian-obligator/assets/309746/5bdf62c7-2854-42eb-9951-9443147f3d3b)

...digging into the issue, I see that the following code changes were made two days ago in commit be3bb0c, same file (main.ts):

![image](https://github.com/Newbrict/obsidian-obligator/assets/309746/20caea77-3bc4-4b36-8c6e-e03bf102a92a)

Note that the search for the most recent note now recurses subfolders.

My daily notes folder contains lots of other things, not just daily notes. I just happen to have an `attachments` folder in a subfolder of my daily notes. Here are its contents:

![image](https://github.com/Newbrict/obsidian-obligator/assets/309746/dad29dfb-7d63-46ac-ace4-825cc31131f9)

Highlighted is the culprit filename (see error message above).

From this, I reason that somehow the above-pasted code that recurses folders is for some reason matching the noted filename `Pasted Image 20231021233045_222` as a valid daily note.

However, it is not a valid daily note. Here is my setting for my daily note name from the Obligator settings pane:

![image](https://github.com/Newbrict/obsidian-obligator/assets/309746/5caabd0c-f91f-40cb-be0f-64de63a2203e)

The 'Date format' is `[Vaults -] YYYY-MM-DD`, which does not match `Pasted Image 20231021233045_222` (I think), so I am not sure why the code above seems to be matching against this filename.

In any case, given the folder recursion and the (seemingly) incorrect match of the noted filename, it would explain the error message - in fact the (incorrect and invalid PNG) file does not have the required terminal header `# 🥕`.

I have not actually debugged the above code to confirm this theory, but it seems pretty clear that this is the issue because Obligator has been working great for me (thanks, I love it!), my last note was just before the noted update to Obligator, now it's broken, and all evidence fits the above.

I would have gotten in and fixed it myself but I am uncomfortable making changes to the plugin without any sense of the reasoning behind the existing changes. But this break seems important enough to report it as an issue.

Let me know if you want me to dig in and try to debug this - I'm very busy but if everybody else is too I will try to find the time to do it. Or, perhaps it could just be reverted to a non-recursive search (though I suspect the real issue is whatever is causing the match on the incorrect filename).

Thanks!

**Comment by Newbrict** [comment]
Thank you for this very detailed bug report. I will look into it tonight and release a fix tonight.

**Comment by Newbrict** [comment]
I was not able to reproduce the behavior that you saw despite creating an attachments folder containing `PNGs` and using the same naming scheme as you. The way I filtered out file names which didn't match was by using this sequence:

```typescript
let last_note = null;
for (let i=0; i < notes.length; i++) {
        const sub_path = notes[i].path.slice(this.settings.note_path.length + 1);
        const note_moment = window.moment(sub_path, this.settings.date_format)
        if (note_moment.isValid() && note_moment.isBefore(NOW, 'day')) {
                last_note = notes[i];
                break;
        }
}
```

I assumed that if I create a moment using that filename and the date format specified, then it would only be valid if it matched -- and that's the behavior I observed, so I'm very confused why it gave an error on your end.

I added a filter which removes all non-`md` filetypes from the `find_all_notes` function. This fixes the issue, but I'm afraid there is still a bug somewhere that I can't reproduce. The fix is published in `3.17.0` Please let me know if you observe any other issue related to this.

**Comment by daniel347x** [comment]
Thanks very much for looking at this - so very odd. I'll be testing this the next couple of days. I'll follow up if there are any problems with the workaround. Odd that the file matched in my case, very odd indeed; wish I had time to dig deeper.

Thanks again.

**Comment by Newbrict** [comment]
> Note that the search for the most recent note now recurses subfolders.

Just as a bit of information, I intentionally check all of the subfolders now because I added support for nested date folders, e.g.:
`YYYY/MM-MMMM/YYYY-MM-DD` is now a valid date format which will create the appropriate directory structure. The only way I could think of finding the last note with an arbitrary directory structure was to get all the files and try to parse their pathstrings using a moment with the same format.

**Comment by Newbrict** [comment]
Oh, also, thanks for using the plugin :)

**Comment by daniel347x** [comment]
Sadly the issue persists even with the update - now the error message indeed picks up a `md` file, but it seems to be some random one somewhere from inside my `Work` folder (the file name it now picks up is `blip-1.md`).

I'll have to debug this when I get the chance and I'll let you know the outcome. Not sure when I'll have time. For the moment I'm just putting the daily note into a dedicated subfolder.

**Comment by daniel347x** [comment]
By the way, this is a great plugin.

For years I've never used "daily notes" because things drown in the history of dozens of dated notes and I never understood how people benefit from that. But this plugin resolves that and suddenly I'm using it as a go-to approach. Hopefully many others will too!

**Comment by Newbrict** [comment]
> Sadly the issue persists even with the update - now the error message indeed picks up a `md` file, but it seems to be some random one somewhere from inside my `Work` folder (the file name it now picks up is `blip-1.md`).

I suspected that might happen, I was worried about it.

I will take a deeper look at it today and try to get it fixed.




> By the way, this is a great plugin.
> 
> For years I've never used "daily notes" because things drown in the history of dozens of dated notes and I never understood how people benefit from that. But this plugin resolves that and suddenly I'm using it as a go-to approach. Hopefully many others will too!

That's exactly how I felt too! Thanks for the kind words :)

**Comment by Newbrict** [comment]
Do you have any plugins which affect the moment library?

**Comment by Newbrict** [comment]
I solved it. There is a strict mode moment parsing which needs to be enabled. Please verify that this fixes your issue.

available in 3.19.0

**Comment by daniel347x** [comment]
Wow, thanks. I was just thinking about forking the repo to debug it by using BRAT. (Maybe there's a better way? Is the JS editable directly in the `.obsidian` folder?

Thanks, let me test this now.

**Comment by daniel347x** [comment]
Woala! Fixed!

So awesome that you addressed this so quickly.

Thanks again!

**Comment by Newbrict** [comment]
> Wow, thanks. I was just thinking about forking the repo to debug it by using BRAT. (Maybe there's a better way? Is the JS editable directly in the `.obsidian` folder?)

I don't know what BRAT is. Each vault has its own plugins folder in `.obsidian` where you can clone this repo to directly and modify the `main.ts` file with `yarn dev` running to produce the `main.js` file that Obsidian uses. Then just make changes and reload the plugin (turn it off and on again).



> Woala! Fixed!
> 
> So awesome that you addressed this so quickly.
> 
> Thanks again!

No problem :)
