### ISSUE TITLE
Optional Daily notes replacement request

### ISSUE THREAD

**Issue by Lyssabet** [Newbrict/obsidian-obligator#15]
Hi,

I've started out using Obligator, and I really like the features behind being able to pre-schedule things in the template using cron. I tend to need to get a broad overview of how things have gone, though, which I've been using the Daily notes in the Calendar plugin for. Would it be possible to have an option to have the Obligator plugin actually directly replace the notes created by the core Daily notes plugin, so that Calendar will recognize that the note exists?

Thank you!

**Comment by Newbrict** [comment]
I think it's possible, I'll think about if it makes sense for me to implement the change. It would require pulling all of the daily note settings out of Obligator and then hooking into the daily note button rather than the Obligator carrot.

Can you share some screenshots of how your calendar plugin works? Obligator right now processes the entire file except for what comes after the terminal heading. If the calendar is adding text to the file, I would have to specifically add support for that which I probably don't want to do (unless I can think of a general solution).

**Comment by Lyssabet** [comment]
It's the Calendar plugin at https://github.com/liamcain/obsidian-calendar-plugin . Every day with a Daily note created shows a mark underneath it in the calendar sidebar, and it has the CTRL + hover preview of the Daily note, so you can reference something from a date on the calendar without having to leave the currently open tab. If there's an upcoming event for a day, you can create the note in advance (though I don't know how that would play out with Obligator). If there's a past date and there was no note created, you can make one by selecting the date in the calendar and following the prompt.

There is another calendar plugin, OZ Calendar, https://github.com/ozntel/oz-calendar , which can be used to see any note that has been created depending on its YAML or file name, but it doesn't allow the preview or week numbering that Calendar does. And the Gregorian preset for the Fantasy Calendar, https://github.com/fantasycalendar/obsidian-fantasy-calendar , which can have any note added to an event and events are tracked on the calendar. It does allow week numbering, but doesn't allow hover previews, though a day can be opened below the calendar in the sidebar.

All of which is to say, if it's not possible, I'll manage with a different calendar than Calendar, but I would really appreciate at least having the option of using Calendar.

![image](https://github.com/Newbrict/obsidian-obligator/assets/76194225/0b0fd026-2177-44be-b8f0-13a70f85d67f)

**Comment by blooest** [comment]
I'm coming into this a bit late, but the Calendar plugin _**is**_ working for me with Obligator notes.
It looks like that plugin, _unless daily Periodic Notes are enabled_, uses the **core Daily Notes settings** even if it's **not enabled**, and if your Obligator note filenames match the format defined there, it seems to pick them up just fine.

Creating a new file through its interface, however, appears to work through its own method using the configuration it has pulled, which is to say that it will not use Obligator's features, and **neither would hooking into the core Daily Notes plugin** *or Periodic Notes for that matter, from what I can tell with my amateur code-reading abilities*.
It looks like you could hook into the plugin's creation method too, if you wanted to, but even putting aside the extra workload I'm not sure you really intend to handle forward/backdated notes in the first place.

**Comment by Newbrict** [comment]
@Lyssabet Can you try to see if your use case is covered by matching the daily notes date format with the Obligator date format as mentioned above?

**Comment by Lyssabet** [comment]
I had already tried that before I commented the first time. I think it's just not working correctly on my computer, though. Obligator timed to-dos (the *** formatted ones) from the template setup are correctly appearing on new Obligator notes, but to-dos from Obligator notes on previous days aren't rolling over to the new day.

**Comment by Newbrict** [comment]
> I had already tried that before I commented the first time. I think it's just not working correctly on my computer, though. Obligator timed to-dos (the *** formatted ones) from the template setup are correctly appearing on new Obligator notes, but to-dos from Obligator notes on previous days aren't rolling over to the new day.

Hm, can you verify that you're on the latest version of Obligator? 3.20.1?

If so, can you show me how to reproduce that? That shouldn't be happening.

**Comment by Lyssabet** [comment]
It is indeed 3.20.1, and to reproduce it: I create an Obligator note one day, and I start a new Obligator note the next day (by selecting the Obligator icon in the left toolbar). The new Obligator note contains everything from the preset template that it should, and none of the new but incomplete to-dos from the previous day's note. They're all new ones a couple of headings before the end heading that's set in the options. I also tried uninstalling and reinstalling it to see if that would make a difference, and tried it in a different vault. No joy.

**Comment by Newbrict** [comment]
![Obsidian_pIxUr3hLFM](https://github.com/Newbrict/obsidian-obligator/assets/1683041/35a36a80-78c0-4973-9d45-f411c07958ba)

I'm unable to recreate your issue, can you take a look at this and tell me what you're doing differently?

**Comment by Newbrict** [comment]
I will close until you respond.
