### ISSUE TITLE
Task Maangement - Delete Tasks or Add Tags

### ISSUE THREAD

**Issue by TheDonkerZ** [Newbrict/obsidian-obligator#18]
Hey there! Thanks for the great work on extending Daily notes; they seemed a bit limited so I didn't use them until finding Obligator!

Was wondering what it would take to to do either of the following;
- automatically delete incomplete tasks when creating a new note

or (more preferably)
- adding a tag to a task when creating a new note

I'm hoping to be able to keep a running track of open tasks I have without having copies upon copies of them sitting in an incomplete state. It's less that it never got checked off, but that I have to manually delete it or add a tag myself that excludes it from tasks filters for Calendars and whatnot.

I think something that looks for incomplete tasks and appends ` #task-name` (incl whitespace), with a setting to specify which tag(s) you'd like it to add.

I wouldn't be opposed to trying to add that myself and submitting a PR, I'm just *very* green in the programming world, so I have no promises with how easily I could do that hah.

**Comment by Newbrict** [comment]
Currently, the archive does not support that. The archive just copies the note out of the hierarchy and puts it flatly inside of the archive directory.

I am inclined to make a change to support archiving in that format, but it will have to wait at least a week since I'm occupied at the moment.


> This is what it currently looks like when I click my Obligator button tomorrow:
Is this correct? Obligator should be deleting template request 1 and its child subtask 1.

**Comment by Newbrict** [comment]
Also I'm still confused on the use case. You want to delete (or tag) *incomplete* to-dos? Why would you want to delete to-dos if they're not complete? That's kind of the opposite of what Obligator does do.

**Comment by Newbrict** [comment]
The archive function now supports a nested structure. Please test and let me know if the issue is resolved.
