### ISSUE TITLE
Delete nested data for finished tasks

### ISSUE THREAD

**Issue by SimonBeau** [Newbrict/obsidian-obligator#19]
Thank you so much for building this plugin. It almost perfectly matches my plugin workflow. I have one feature request.

As I work on todos, I sometimes add nested notes below them as bullet points.

- [ ] Task
	- Ongoing notes related to the task
	- More notes 

 I love that these come over with your plugin. However, when I complete a task I would like  to not bring over any nested bullet points as these belong to the completed task from the previous day.

I'm curious if this is something that would help other people's workflows as well?

**Comment by Newbrict** [comment]
Can you provide a full example showing the before and after behavior that you're looking for?

**Comment by SimonBeau** [comment]
_Input Note:_

## 2023-12-05
- [x] Task A
    - ongoing notes related to the task
    - More notes
- [ ] Task B
    - ongoing notes related to the task
    - More notes

---
_Current new note:_

## 2023-12-06
    - ongoing notes related to the task
    - More notes
- [ ] Task B
    - ongoing notes related to the task
    - More notes

---
_Desired behaviour_

## 2023-12-06
- [ ] Task B
    - ongoing notes related to the task
    - More notes

**Comment by Newbrict** [comment]
I see.

I think the new behavior you suggest is how it should be working.

I'm going to actually mark this as a bug.

I'll be adding this, probably later this week or early next week.

Thanks.

**Comment by Newbrict** [comment]
@SimonBeau Hi, I decided to just fix it now. Please update to 4.0.0 and verify that this works as you expected.

**Comment by SimonBeau** [comment]
So fast! That works perfectly, thank you

**Comment by Newbrict** [comment]
> So fast! That works perfectly, thank you

You're welcome.
