### ISSUE TITLE
It Should Be Possible to Have Tasks at the Top or Bottom of a Note

### ISSUE THREAD

**Issue by matsieftw** [Newbrict/obsidian-obligator#23]
Right now, we are only able to set a "terminal heading" where carry over must exist at the top of the note. I'd prefer to have my action items at the bottom of my note. Being able to set both the beginning and ending bounds would be really helpful.

**Comment by Newbrict** [comment]
I actually had this feature and then deleted it because I thought it was too complicated for most people -- but that's because I had it as the only behavior. I think I can add it as an optional setting. I'll set it as a feature request. Thanks.

**Comment by Newbrict** [comment]
This feature is present in 5.1.0

Please update, test, and let me know.

Terminal headings are now optional.
