### ISSUE TITLE
Nothing is copying over and macros don't work

### ISSUE THREAD

**Issue by matsieftw** [Newbrict/obsidian-obligator#24]
I've tried uninstalling and reinstalling. I've installed via the community plugin portal in Obsidian. No content copies over to the next day and the template macros for "previous note" etc don't work. Not sure what I need to do to fix this.

I've tried adding the `{{ obligator * * * }}` to all my headings both in the template and then manually in the previous note. Nothing copies over. Clicking the carrot creates a new daily note, but just from my template. No rollover. Not sure what I'm missing from set up. Reading through the README and issues didn't really give me any guidance for troubleshooting either. 

Whether I use the Carrot icon to create the new note or Obligator creates the note at start up, the only thing that happens is a new daily note is made using my template.

**Comment by matsieftw** [comment]
![Screenshot 2024-01-09 at 9 20 27 AM](https://github.com/Newbrict/obsidian-obligator/assets/7517184/8e3b1af6-cc26-47da-95c1-1de20e7e7ee9)

![Screenshot 2024-01-09 at 9 20 44 AM](https://github.com/Newbrict/obsidian-obligator/assets/7517184/f46904a0-0619-49b3-87fc-9e90875d4097)

![Screenshot 2024-01-09 at 9 21 07 AM](https://github.com/Newbrict/obsidian-obligator/assets/7517184/96d1d0f9-57df-46c9-a0aa-b1cd9d7d4c03)

**Comment by matsieftw** [comment]
I have set the terminal heading to my own H2 and to the carrot I copied and pasted from your example. I've tried adding any of the macros.

It successfully creates new daily notes, but just from the template with no carry over.

**Comment by Newbrict** [comment]
I think the issue is that leading slash in your new file location.

Can you try removing that and testing again?

**Comment by matsieftw** [comment]
Okay, now it does carry over my checklist under action items, but the behavior is still not good. It carries over yesterday's date heading, but not any of the headings under my checklist (1-on-1s & its subheadings and Engineering Sync).

It is also sandwiching the carryover items under the copy from template of those headings.

So it goes _**copied from template**_: H2 Today's date > H3 Action Items > H4 1-on-1s > H5 individual 1-on-1s > H4 Engineering Sync

then _**copied from previous notes**_: H3 Action Items > checklist from under H3.

![Screenshot 2024-01-09 at 9 49 19 AM](https://github.com/Newbrict/obsidian-obligator/assets/7517184/33d878d4-a7c1-4759-9638-5c2446b318f6)

**Comment by Newbrict** [comment]
I see what's going on.

I don't keep a tie between macros and what their output was. All I do is compare the templated/macro'd file with what the old file looks like, and perform a merge within the heirarchical structure.

Because the heading has macro'd information, each new template will make a new heading.

I'm not sure if I can think of a good way to make it behave in the way you're thinking (determine that that heading is macro'd, and replace it with the newly macro'd heading). To get away from that issue for now, the only option is to only use the date macro after the carrot, or wherever you intend for it to carry over with each new note.

Perhaps #23 can allow something similar to the behavior you're after, whenever I implement it.

**Comment by matsieftw** [comment]
hmm. But what about all the subheadings that are supposed to be between Action Items and the Carrot that aren't carried over from the previous day? The blank versions are being copied from the template and placed above the copied over info.

**Comment by Newbrict** [comment]
> hmm. But what about all the subheadings that are supposed to be between Action Items and the Carrot that aren't carried over from the previous day? The blank versions are being copied from the template and placed above the copied over info.

If you expand those action items under "08 January 2024, Monday" does it contain everything that you expected? It's carrying them over under that heading, and then creating a new structure under the newly macro'd "09 [...]" heading.

**Comment by matsieftw** [comment]
No. It only copied the checkboxes, not any of the headings from the previous day. I collapsed them because they have sensitive information. The headings were only copied from the template, that's why they're above the carried over yesterday's date and checkboxes. They should be under Action Items -- see the template image I posted initially.

**Comment by Newbrict** [comment]
Are you able to create a template and and daily note file that I can use to locally recreate the issue? I don't have thi issue and I'm not sure how to recreate it.

Alternatively you can add me on Discord if you're okay debugging it with me that way.

**Comment by matsieftw** [comment]
I am open to both! Happy to take this troubleshooting out of github issues since it feels like a poor place for a specific support issue.

**Comment by Newbrict** [comment]
I'm "Objectivist" on Discord.

**Comment by matsieftw** [comment]
If anyone sees this:

My big issue was resolved by removing the leading slash in my "New Note Directory" settings. I had `/daily` and needed to change it to just `daily`.
