### ISSUE TITLE
Days of the week not working?

### ISSUE THREAD

**Issue by sjee** [Newbrict/obsidian-obligator#28]
So, I've added some obligate macros to a template. When creating a new daily note the content of the template gets placed into the new daily note (as do old tasks from the previous day). But when I want do add lines/tasks based on a day of the week, they don't get added to the daily note. 

Doing this on **Sunday 25 February**:

```markdown
## Personal tasks
Some text...
{{ obligate * * * }}     👈  🟢 does work
Some more text
{{ obligate * * 7 }}     👈  🔴 does not work
- sunday
{{ obligate 25 2 7 }}    👈  🔴 does not work
- [ ] sunday 25 february
{{ obligate 25 * * }}    👈  🟢 does work
- the 25th
{{ obligate 1,25 * * }}  👈  🟢 does work
- the 1st and 25th
```

Seeing as it is currently Sunday 25 February, I would expect `{{ obligate * * 7 }}`  and `{{ obligate 25 2 7 }} ` to render the next lines. But they do not. Am I missing something?

At the time of this writing I'm on MacOS 14.2.1 with Obsidian 1.5.8

**Comment by Newbrict** [comment]
The reason it's not working is because the day of the week is actually zero indexed, see:
https://momentjs.com/docs/#/get-set/day/

Switch your sunday to be 6 and it will work. I see that I have some erroneos examples in my example note.

**Comment by sjee** [comment]
Ah, that sounds logical. I tried this:

```markdown
{{ obligate * * 6 }}
- Sunday (zero indexed)
{{ obligate 25 2 6 }}
- [ ] Sunday 25 February (zero indexed)
{{ obligate 25 * * }}
- the 25th
{{ obligate 1,25 * * }}
- the 1st and 25th
```

...but that too did not work. However, you pointed me in the right direction by refering to _Moment.js_. In the paragraph you linked to it stated:

> This method can be used to set the day of the week, with Sunday as 0 and Saturday as 6. If the value given is from 0 to 6, the resulting date will be within the current (Sunday-to-Saturday) week.

So, you were correct about it being zero-indexed, but _Moment.js_ starts its weeks on a Sunday, not a Monday.

So this works:

```markdown
🟢 SOLUTION

{{ obligate * * 0 }}
- Sunday (zero indexed)
{{ obligate 25 2 0 }}
- [ ] Sunday 25 February (zero indexed)
{{ obligate 25 * * }}
- the 25th
{{ obligate 1,25 * * }}
- the 1st and 25th
```

@Newbrict Thank you for pointing me in the right direction.

**Comment by Newbrict** [comment]
Ah, I see. Glad you figured it out. I recommend this tool for validating the syntax:
https://crontab.guru/#5_4_*_*_0
