### ISSUE TITLE
Add a {{ next_daily_note }} template option

### ISSUE THREAD

**Issue by TjeerdA** [Newbrict/obsidian-obligator#3]
Apart from the generated link to the previous daily note, I would also like a link to the next note (if it already exists) so it is easy to go through a sequence of days. Is that a possibility?

**Comment by Newbrict** [comment]
This is possible, but a bit weird because it would have to be ignored from the template file, then templated on the source file. But it can be done. I will think about how to do it and implement it next week most likely.

**Comment by Newbrict** [comment]
@TjeerdA I added this feature in 3.9.0 with the macros:
`{{next_note}}`
and
`{{next_note_path}}`

Please give it a try.

**Comment by Newbrict** [comment]
Version `3.10.0`*
