### ISSUE TITLE
New Today's Note doesn't find previous notes or finds the wrong one

### ISSUE THREAD

**Issue by Pachtjuilaard** [Newbrict/obsidian-obligator#30]
I've used this plugin in two vaults, my existing vault and a clean new one. In the existing vault, every new Daily Note sees exactly the same earlier Daily Note as the previous one. In that vault, every new Daily Note copies the text from a note called 02-02-2024 instead of the note from yesterday. I've set the date format to DD-MM-YYYY.

In the new vault, I've made a note called 2024-03-26 and made a new Daily Note using this plugin. The new Daily Note doesn't find a previous note, despite using the exact same template.

The plugin settings also aren't respected in the new vault, I've set an Initial Heading and a Terminal Heading, but the template is still copied from beginning to end when I make a new Daily Note.

**Comment by Newbrict** [comment]
2024-03-26 is YYYY-MM-DD format, is that what your new note format is set to in the settings?

**Comment by Pachtjuilaard** [comment]
It is in the new vault! My existing vault has daily notes in the DD-MM-YYYY format, and the Obligator settings are the same.

**Comment by Newbrict** [comment]
@Pachtjuilaard 
I have not been able to reproduce this. Obligator works property when I test these cases.
Are you sure you're changing the Obligator settings (not the daily note settings) and you're clicking the Obligator carrot icon (not the daily note icon)?

**Comment by Pachtjuilaard** [comment]
It seems like the problem has mostly resolved itself, without me changing any of the settings lately. Previous days are now found correctly. I'm sure I've checked the Obligator settings earlier, and when I checked just now it was in DD-MM-YYYY format.

Thanks anyway for looking into it!
