### ISSUE TITLE
Nested "checked" -> "unchecked" -> "checked" -> "unchecked" chain only copies first level of "unchecked" to the next date 

### ISSUE THREAD

**Issue by daniel347x** [Newbrict/obsidian-obligator#31]
I love the feature of Obligator in which checked items are automatically removed on the next date's note.

A great edge case is when some parent item is checked but a child item isn't - the next date's note still contains the parent item, and you therefore see the child item (as desired).

However, a further edge case exhibits a bug: when there is a chain of "checked" -> "unchecked" -> "checked" -> "unchecked" items. In this case, it seems only the first level of "nesting" of the "unchecked" items are carried over to the next date's note.

Screenshots of a a before/after scenario follow:

BEFORE (Note for Date A):

![image](https://github.com/Newbrict/obsidian-obligator/assets/309746/fc864520-d1b6-4e43-ab4a-95a5c0923f06)

AFTER (Note for Date B, the next note following Date A):

![image](https://github.com/Newbrict/obsidian-obligator/assets/309746/ec1460a5-cbb7-4d71-9a8f-145de640cd09)

You can see from the screenshots that only the first "level" of unchecked items was carried over. Specifically, the second "level" unchecked item - "Leave Oona-Gold on until months and all Backblaze is complete..." - was not carried over to the next note.

Hopefully at some point you or somebody may have time to get this bug ironed out!

Love this plugin! I use it regularly. Thanks!

**Comment by Newbrict** [comment]
Thanks for the report, I'll try to find some time to look into it.

**Comment by Newbrict** [comment]
@daniel347x Hi, I am unable to recreate this issue. I tested with a stripped down version of the example you gave. Is it possible that the note was not saved when you clicked "today's obligator note?" If you had just unchecked that, then clicked, the last note may not have been written.

**Comment by Newbrict** [comment]
![image](https://github.com/Newbrict/obsidian-obligator/assets/1683041/7ee45e98-e234-4a4e-983a-3398d40f969b)

**Comment by daniel347x** [comment]
OK, I cannot reproduce it myself:

![image](https://github.com/Newbrict/obsidian-obligator/assets/309746/0ad0b843-39a2-4065-a69a-b26883839d02)

I am quite meticulous so there must have been some edge case I struck in the original posting, but it very well may be unrelated to the issue described.

Thanks! Seems the issue can be closed.
