### ISSUE TITLE
Schedule tasks with specific date. FutureTasks.md - Not in template.md

### ISSUE THREAD

**Issue by gregorylearns** [Newbrict/obsidian-obligator#32]
Hi! Thanks for the excellent addon! Been loving it and using it daily!

I would like to ask if there's a way that it can imitate the "Future Log" feature of a bullet journal? I've been reading the docs and experimenting and I think the way to do something like this currently is with the template file.
![Future log](https://i.ytimg.com/vi/l1r48EyeCco/maxresdefault.jpg)

Basically Something where you would put a certain date for a certain task and it would be added to the journal on that day.
Like
`FutureTasks.md`
```
2024-05-24
## Personal Task
- [ ] Go to vet
## Work
- [ ] Meet with John at 9pm
2024-06-04
## Personal Task
- [ ] Go to Elizabeth's Party
## Work
- [ ] Catch up on the Remote Team
```

The way I thought about it is having a separate file for future log. In addition to template, there would be another file for future log, which could be optional?

Forgive me if this feature is currently available, I've been studying the readme.md but I haven't found a way that does not include and clogging up the template file

I would love to help out but I dont know how to code in TypeScript. Thank you so much for the work!

**Comment by Newbrict** [comment]
Hello,

I'm glad you're enjoying the plugin :)

I believe the behavior you want is already implemented in Obligator with the obligate macro.

See the [example file](https://raw.githubusercontent.com/Newbrict/obsidian-obligator/master/example/daily_note.md)

Specifically, this segment:
```
{{ obligate 20 10 * }}
- [ ] on the 20th of October
```

This macro would put an item specifically on October 20th. Is that the behavior you're looking for?
