### ISSUE TITLE
Daily Note not moving to yesterday's notes folder

### ISSUE THREAD

**Issue by bradengv** [Newbrict/obsidian-obligator#34]
The Daily Note rolls over and performs as expected, but the yesterday's note stays and sometime stacks the past two or three days together. I have also had it where it pulled a daily note from over a month ago into the current daily notes section. This can cause duplicates of notes to be created into yesterday's notes folder as well. 

I am using two windows computers on a paid, sync'd obsidian remote vault. We are also using two iPhones on this vault alongside the computers. I love the plugin, and have been getting by with just manually moving them myself. I wanted to bring this up in case it's a simple fix on my end or a true bug. I can provide whatever extra details you may need. 

Three screenshots are attached for clarity of the situations I have encountered. 

![Screenshot 2024-09-20 101938](https://github.com/user-attachments/assets/53d7ae0d-ad7f-4cbe-9715-a0df6091ed1a)
![Screenshot 2024-09-20 102017](https://github.com/user-attachments/assets/300c1992-11f0-464d-985a-1ef65f506687)
![Screenshot 2024-09-20 102036](https://github.com/user-attachments/assets/e2e9cd34-8e51-4e68-b34d-4e395ed68923)

**Comment by Newbrict** [comment]
Do you have the "open on startup" feature enabled? If you have sync'd vaults, that feature might create new daily notes before the sync occurs, and if you had a newer note on the other computer, it would cause this.

**Comment by bradengv** [comment]
> Do you have the "open on startup" feature enabled? If you have sync'd vaults, that feature might create new daily notes before the sync occurs, and if you had a newer note on the other computer, it would cause this.

Howdy sir, I did not realize you responded so quickly back when I made this ticket. I am so sorry I did not see it. We do not have "open on startup" enabled. We are still encountering this issue

**Comment by Newbrict** [comment]
> > Do you have the "open on startup" feature enabled? If you have sync'd vaults, that feature might create new daily notes before the sync occurs, and if you had a newer note on the other computer, it would cause this.
> 
> Howdy sir, I did not realize you responded so quickly back when I made this ticket. I am so sorry I did not see it. We do not have "open on startup" enabled. We are still encountering this issue

Do you have Discord or Teams? It would be useful if you can demonstrate the issue to me on a screenshare.

**Comment by bradengv** [comment]
> > > Do you have the "open on startup" feature enabled? If you have sync'd vaults, that feature might create new daily notes before the sync occurs, and if you had a newer note on the other computer, it would cause this.
> > 
> > 
> > Howdy sir, I did not realize you responded so quickly back when I made this ticket. I am so sorry I did not see it. We do not have "open on startup" enabled. We are still encountering this issue
> 
> Do you have Discord or Teams? It would be useful if you can demonstrate the issue to me on a screenshare.

Yes sir I have teams. Are you free now?

**Comment by Newbrict** [comment]
> > > > Do you have the "open on startup" feature enabled? If you have sync'd vaults, that feature might create new daily notes before the sync occurs, and if you had a newer note on the other computer, it would cause this.
> > > 
> > > 
> > > Howdy sir, I did not realize you responded so quickly back when I made this ticket. I am so sorry I did not see it. We do not have "open on startup" enabled. We are still encountering this issue
> > 
> > 
> > Do you have Discord or Teams? It would be useful if you can demonstrate the issue to me on a screenshare.
> 
> Yes sir I have teams. Are you free now?

I'm not but I might be later

Send me an email with your information please

**Comment by Newbrict** [comment]
Issue should be resolved.
