### ISSUE TITLE
Settings appear to work but actual obligate statements not firing

### ISSUE THREAD

**Issue by Takenote61** [Newbrict/obsidian-obligator#36]
New to plugin. I changed the settings per the video. New notes are being created with the file structure I put in the settings. However. using the example template, the statements are coming across either 1) with the {{ obligate _whatever_}} or 2) without that but statements don't appear to be executing.

Example:

![image](https://github.com/user-attachments/assets/b89acd98-34cf-46e5-b7b5-b2c98005404b)

**Comment by Newbrict** [comment]
Are you using the little carrot icon to create the note, or the daily note icon?

**Comment by Takenote61** [comment]
Created with the carrot. Using the daily note icon doesn't use the
obligator at all.

**Comment by Newbrict** [comment]
Can you post your template file

**Comment by Takenote61** [comment]
![image](https://github.com/user-attachments/assets/e5ac265e-8305-4dab-aa76-63febf7af339)

**Comment by Newbrict** [comment]
> ![image](https://private-user-images.githubusercontent.com/182418284/370093831-e5ac265e-8305-4dab-aa76-63febf7af339.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzg1MjAsIm5iZiI6MTcyNzE3ODIyMCwicGF0aCI6Ii8xODI0MTgyODQvMzcwMDkzODMxLWU1YWMyNjVlLTgzMDUtNGRhYi1hYTc2LTYzZmViZjdhZjMzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxMTQzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDI4NGVmZWVlYzAyMzkxNWE5MjA1YjkxMTQxMGFhNjdkMzg3YzdiNmViZjhiMGQ3MjRiYTE0ODFjZTllOWM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oVH4mAc5g-Mm5riAKMVa6BZuog5n6d9Mh5UX3iemq9w)

The format of the macro is incorrect:
> The obligate macro will add the immediately proceeding line. If the date matches for any day between your last note and today. See the [example template file](https://github.com/Newbrict/obsidian-obligator/blob/master/example/daily_note.md) for plenty of common examples. If you are confused about this and want some help, just open a GitHub issue.

**Comment by Newbrict** [comment]
Maybe this is confusing because GitHub tries to format it?

Try the raw view:

https://raw.githubusercontent.com/Newbrict/obsidian-obligator/refs/heads/master/example/daily_note.md

**Comment by Newbrict** [comment]
Did this fix your issue?

**Comment by Takenote61** [comment]
Yes, my fiddling around eventually got it. Thanks.
