### ISSUE TITLE
Rollover no longer working

### ISSUE THREAD

**Issue by msdosfx** [Newbrict/obsidian-obligator#39]
Everything was working great for many months, but a few days ago my rollover started failing. One checked item has rolled over as an unchecked, and several unchecked items aren't rolling over at all.  Template has some personal info in it so I don't really want to post it publicly here. Perhaps a breaking update to Obsidian was rolled out 3 or 4 days ago? Obsidian Flathub Linux. I am happy to share whatever directly via email or however, but don't really want to just post it publicly here.

**Comment by DimitDimit** [comment]
Hi @msdosfx, it still works for me so I don't think it's the new version.

Are you using Obligator on multiple devices set up with sync? Also, are you using the "new note on startup" feature on multiple devices?

**Comment by Newbrict** [comment]
Hi @msdosfx, it still works for me so I don't think it's the new version.

Are you using Obligator on multiple devices set up with sync? Also, are you using the "new note on startup" feature on multiple devices?
