### ISSUE TITLE
example/daily_note.md error in cron descriptions

### ISSUE THREAD

**Issue by edusanzio** [Newbrict/obsidian-obligator#40]
I was trying to understand the cron codes but it wasnt making sense, then i discovered the it was shifted by one line, also it would be worth mentioning that it doesn't use the full cronjob code, only the last three (not time and minutes)

**Comment by Newbrict** [comment]
From the README:

> {{ obligate * * * }} is a very powerful macro. It lets you set up recurring to-do items in your template. It uses a simplified version of the cron syntax, where the asterisk represent day-of-the-month, month-of-the-year, and day-of-the-week in that order.

Is this insufficient?
