### ISSUE TITLE
Will Obligator be able to do this?

### ISSUE THREAD

**Issue by vogelap** [Newbrict/obsidian-obligator#5]
The Obligator plugin looks very exciting! I am using Obsidian (at the Supporter level) to manage my daily to-do items, and currently enjoy the “Rollover Daily Todos” plugin which rolls yesterday’s to-do items to today’s daily note.

- Support naming of notes like "[Daily]/YYYY/MMMM/YYYY-MM-DD" to create: 
<img width="115" alt="image" src="https://github.com/Newbrict/obsidian-obligator/assets/1869371/081916ac-120c-495d-9f24-a2c80f2f630e">

- Open Daily Note on Startup
- Automatic rollover on Daily Note open
- To-Do Sort ("completed at top" or "completed at bottom") to automatically sort completed to-do items (the "To Do Sort" plugin currently does this, but perhaps Obligator could handle it as well).

I recently installed the Things theme (2.1.19) which enabled the “[/]” Task Status for ‘In Progress’ items (among other useful task statuses that I'd like to use).

- I’d like to know if the Obligator plugin can roll over ALL to-do items from yesterday to today’s daily note that are NOT in a status of complete (“[x]”). Is there a way to do that? I envision a regex that excluded only “[x]” but included all other bracketed items (like “[/]”) to be rolled over from day to day. But I lack the skills to implement that…

https://forum.obsidian.md/t/rollover-daily-todos-rollover-task-statuses/70875

**Comment by Newbrict** [comment]
> I’d like to know if the Obligator plugin can roll over ALL to-do items from yesterday to today’s daily note that are NOT in a status of complete (“[x]”). Is there a way to do that? I envision a regex that excluded only “[x]” but included all other bracketed items (like “[/]”) to be rolled over from day to day. But I lack the skills to implement that…

Currently, Obligator will only delete `[x]` styled checkbox items, it will keep unchecked `[ ]` and "in progress" `[/]` items.

> Automatic rollover on Daily Note open
Obligator already does this, but not through the Daily note function. It replaces the Daily note function. Just press the carrot icon: 
![image](https://github.com/Newbrict/obsidian-obligator/assets/1683041/19e61623-3494-4d8e-adbe-db683ebbf95b)

> Support naming of notes like "[Daily]/YYYY/MMMM/YYYY-MM-DD" to create:
> Open Daily Note on Startup

These are good suggestions, I'll keep them inmind. A naming style like that might make my archiving feature obsolete, but I think it's an improvement over the current design. I'll open up features for those later.

**Comment by vogelap** [comment]
Thank you for your reply and information. I appreciate it. I'm glad to see the plugin receiving frequent updates.

You said:

> Currently, Obligator will only delete [x] styled checkbox items, it will keep unchecked [ ] and "in progress" [/] items.

How will it handle OTHER styled checkbox items (for example, [?], or [!], etc.)? I hope it deletes ONLY [x] style and will pass the rest...

You said:

> Obligator already does this (Automatic rollover of Daily Note option), but not through the Daily note function. It replaces the Daily note function. Just press the carrot icon.

If this could be made automatic on startup, that would be ideal for my use case.

You said:

> Support naming of notes like "[Daily]/YYYY/MMMM/YYYY-MM-DD"

This functionality is crucial to my use case, so I sincerely hope it is something you can support!

Thanks again. I look forward to seeing Obligator continue to grow!

**Comment by Newbrict** [comment]
> How will it handle OTHER styled checkbox items (for example, [?], or [!], etc.)? I hope it deletes ONLY [x] style and will pass the rest...

The filtering logic is based on the [x] styled check boxes. It will only delete those.

However, I use a regular expression to detect all types of checkbox, what are the different types that people use? I wasn't even aware of [/] until yesterday. I can add all the types to my regular expression.

**Comment by Newbrict** [comment]
> Support naming of notes like \"[Daily]/YYYY/MMMM/YYYY-MM-DD\

Out of curiosity, is this something that rollover-daily-notes supported? (Is that what you have been using?)

**Comment by vogelap** [comment]
> > How will it handle OTHER styled checkbox items (for example, [?], or [!], etc.)? I hope it deletes ONLY [x] style and will pass the rest...
> 
> The filtering logic is based on the [x] styled check boxes. It will only delete those.
> 
> However, I use a regular expression to detect all types of checkbox, what are the different types that people use? I wasn't even aware of [/] until yesterday. I can add all the types to my regular expression.

https://publish.obsidian.md/tasks/Getting+Started/Statuses. Check the Tasks (community plugin) for details. These are what I've got added to my Obsidian. I mainly use [ ], [/], [!], and [?]. These are the ones I've got configured (I don't use all of these; just wanted to show you what's out there)... 
<img width="361" alt="image" src="https://github.com/Newbrict/obsidian-obligator/assets/1869371/50e64802-225c-4460-9a20-7aca4e279556">

> > Support naming of notes like "[Daily]/YYYY/MMMM/YYYY-MM-DD\
> 
> Out of curiosity, is this something that rollover-daily-notes supported? (Is that what you have been using?)
No, this is supported by the Daily Note core plugin.
<img width="586" alt="image" src="https://github.com/Newbrict/obsidian-obligator/assets/1869371/bfb8c100-b8be-4b6b-a30b-8ed2164471e5">

**Comment by Newbrict** [comment]
Got it, thanks.

**Comment by Newbrict** [comment]
@vogelap I added some of these features.

I have a separate issue open for #7

Could you please open whatever other feature requests you had as separate issues? This issue is a bit messy for me, I'm not sure what's left.
