### ISSUE TITLE
Nested folder name support.

### ISSUE THREAD

**Issue by Newbrict** [Newbrict/obsidian-obligator#7]
As mentioned in #5.

My concern is that it will be annoying to archive notes like that, however, if notes are that well organized, is archiving necessary? Probably not. This seems like a good feature.

**Comment by vogelap** [comment]
This would be awesome to have! 

The ability to support Nested Naming (like "[Daily]/YYYY/MMMM/YYYY-MM-DD") is crucial to my use case. It's more important to me than Archiving support inside Obligator.

**Comment by Newbrict** [comment]
This is available in 3.15.0

**Comment by vogelap** [comment]
Thank you! This is awesome!

The only thing holding me back from switching over to it is https://github.com/Newbrict/obsidian-obligator/issues/13!
