### ISSUE TITLE
Properties are being copied from the previous note

### ISSUE THREAD

**Issue by Jamalam360** [Newbrict/obsidian-obligator#9]
Template:
```md
---
tags:
  - daily-note
created: "{{date}} {{time}}"
---
## TO-DO List
## Daily Notes
---
Previous Note: [[{{previous_note_path}}|{{previous_note}}]]
```

Previous note:
```md
---
tags:
  - daily-note
created: "2023-11-09 10:58"
---
Test
## TO-DO List
- [/] Test
## Daily Notes
---
Previous Note: [[2023-11-08]]
```

Newly created note:
```md
---
tags:
  - daily-note
created: "2023-11-13 11:34"
---
created: "2023-11-09 10:58"
Test
## TO-DO List
- [/] Test
## Daily Notes
---
Previous Note: [[Daily Notes/2023-11-09.md|2023-11-09]]
```

Seems as though it is  incorrectly copying the `created` property over. IMO the plugin should just discard properties if present

**Comment by Newbrict** [comment]
I have never used properties so I didn't even know they existed. Currently obligator just copies every from the beginning of the file until the terminal heading. I'll look into how to fix that to be compatible with properties.

**Comment by Newbrict** [comment]
For the moment you can either manually delete the duplicate properties or not use them. But I'll get this fixed up soon.

**Comment by Newbrict** [comment]
@Jamalam360 Please try out release 3.8.0 and let me know if your issue is fixed. It should be.

**Comment by Newbrict** [comment]
Also, formatting with the date & time property works nicely with the template, see:
![2023-11-13-145215_483x143_scrot](https://github.com/Newbrict/obsidian-obligator/assets/1683041/95677899-e706-422a-b934-0e41db38ce9c)
![2023-11-13-145301_378x149_scrot](https://github.com/Newbrict/obsidian-obligator/assets/1683041/1f0a3436-282b-4c91-bdaf-83cf1bb70b42)

**Comment by Jamalam360** [comment]
:+1: :+1: all working here, thank you for the quick turnaround and for the plugin!

**Comment by Newbrict** [comment]
> 👍 👍 all working here, thank you for the quick turnaround and for the plugin!

Glad you like it!
